### ISSUE TITLE
Add explicit link to the open source.

### ISSUE THREAD

**Issue by x-N0** [DashboardHub/Website#145]
**Motive:** Had to scroll to the bottom to click the github icon.

**Fix idea:** Add a hyperlink in the section where's the open source explanation.

**Img:**
![imagen](https://user-images.githubusercontent.com/51316342/79406690-beef4e00-7f65-11ea-813f-c38e94a82210.png)
There should be the **hyperlink**, I suggest to put it where it says "DashboardHub" or "community".

**Comment by eddiejaoude** [comment]
Good idea, thank you 👍
