### ISSUE TITLE
Header goes offscreen

### ISSUE THREAD

**Issue by duskok** [DashboardHub/Website#31]
The header content is not responsive and on 1366x768 resolution goes of screen (the top is cutoff)
![image](https://user-images.githubusercontent.com/27017480/39722936-764f7558-5244-11e8-8bd1-d6020c3649b2.png)

**Comment by eddiejaoude** [comment]
Good spot, thank you! 👍

**Comment by eddiejaoude** [comment]
Fixed in new design
