### ISSUE TITLE
www. to redirect to dashboardhub.io

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/Website#4]

**Comment by andrew-cunliffe** [comment]
Isn't that the wrong way around should be fashboardhub.io to www.dashboardhub.io search engines give better results to fully qualified domains, I know in the past people went through a phase of dropping the www part.

**Comment by eddiejaoude** [comment]
Really? If that is the case, I can swap them around. I wasn't aware it effect the search engines. 

I just did a quick google and found this, not sure how true it is? http://www.wpbeginner.com/beginners-guide/www-vs-non-www-which-is-better-for-wordpress-seo/

Thoughts?

**Comment by andrew-cunliffe** [comment]
Interesting, I thought the opinion had changed now as people have api.domain.tld, docs.domain.tld, content.domain.tld, cdn.domain.tld, etc, etc, as such I though the latest is you have www.domain.tld and send domain.tld to your 'default' sub-domain and as such search engines will give (a tiny amount extra) for having the 'correct' structure but perhaps wordpress have the right thing I don't know that logic in google for deciding who comes where, but they do say 'google' what about the others (which not many people use), however I would they are right as that is pretty much their business.

Anyhow I prefer to be specific about the job a site is doing so i suppose i fall into the www camp, and maybe it is a preference thing, but when you have lots of subdomains i do think being specific helps and most people say it should be that way around (that I talk to anyhow).
